apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: microservices
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus-service:9090']

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector-service:8889']
        honor_labels: true
        metrics_path: /metrics