apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        args:
        - "-config.file=/etc/tempo.yaml"
        ports:
        - containerPort: 3200
          name: http
        - containerPort: 4317
          name: otlp-grpc
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3200
          initialDelaySeconds: 45
          periodSeconds: 10
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo.yaml
          subPath: tempo-config.yaml
        - name: tempo-data
          mountPath: /tmp/tempo
      volumes:
      - name: tempo-config
        configMap:
          name: tempo-config
      - name: tempo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: microservices
spec:
  selector:
    app: tempo
  ports:
  - port: 3200
    targetPort: 3200
    name: http
  - port: 4317
    targetPort: 4317
    name: otlp-grpc